export const tableData = [
    {
        "id": 1,
        "Merchant": "Freepik & Flaticon",
        "MerchantImage": "http://127.0.0.1:8000/images/table/freepic.svg",
        "Category": "SPENDING",
        "SubCategory": "Other",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/otherCategory.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 2,
        "Merchant": "Amazon",
        "MerchantImage": "http://127.0.0.1:8000/images/table/img.svg",
        "Category": "SPENDING.",
        "SubCategory": "Shopping",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/shoppingIcon.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 3,
        "Merchant": "The Home Depot",
        "MerchantImage": "http://127.0.0.1:8000/images/table/homeDepot.svg",
        "Category": "SPENDING",
        "SubCategory": "Shopping",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/shoppingIcon.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "Pending",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 4,
        "Merchant": "Trader Joe’s",
        "MerchantImage": "http://127.0.0.1:8000/images/table/trader.svg",
        "Category": "SPENDING",
        "SubCategory": "Shopping",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/shoppingIcon.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 5,
        "Merchant": "McDonald’s",
        "MerchantImage": "http://127.0.0.1:8000/images/table/mcdonalds.svg",
        "Category": "SPENDING",
        "SubCategory": "Restaurants & Bars",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/restaurant.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 6,
        "Merchant": "Spotify",
        "MerchantImage": "http://127.0.0.1:8000/images/table/spotify.svg",
        "Category": "SPENDING",
        "SubCategory": "Digital",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/smartfone.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 7,
        "Merchant": "Volkswagen",
        "MerchantImage": "http://127.0.0.1:8000/images/table/volkswagen.svg",
        "Category": "SPENDING",
        "SubCategory": "Automotive",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/car.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 8,
        "Merchant": "Netflix",
        "MerchantImage": "http://127.0.0.1:8000/images/table/netflix.svg",
        "Category": "SPENDING",
        "SubCategory": "Entertainment",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/film.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    },
    {
        "id": 9,
        "Merchant": "Facebook",
        "MerchantImage": "http://127.0.0.1:8000/images/table/fb.svg",
        "Category": "SPENDING",
        "SubCategory": "Digital",
        "SubCategoryImage": "http://127.0.0.1:8000/images/table/smartfone.svg",
        "Institution": "Chase",
        "InstitutionImage": "http://127.0.0.1:8000/images/table/shoppingIcon2.svg",
        "Account": "Chase Freedom 7470",
        "Status": "PENDING",
        "Date": "Dec 9, 2020",
        "Amount": "$11.90",
        "AmountEye": "http://127.0.0.1:8000/images/table/fiEye.svg",
    }
]
